export const listCourse = [
    'Kinh tế vi mô',
    'Kinh tế vĩ mô',
    'Cơ Sở Lập Trình',
    'Kinh tế phát triển',
    'Kinh tế lượng',
    'Kinh tế môi trường',
    'Lịch sử các học thuyết kinh tế',
    'Kinh tế công cộng',
    'Toán cao cấp',
    'Triết học Mác Lênin',
    'Kinh tế chính trị Mác Lênin',
    'Phương pháp nghiên cứu khoa học',
    'Đại Số Tuyến Tính',
    'Nhập Môn Tin Học',
    'Chủ nghĩa xã hội khoa học',
    'Pháp luật đại cương',
    'Toán xác suất',
    'Lịch sử đảng cộng sản Việt Nam',
    'Logic học',
    'Tư tưởng Hồ Chí Minh',
    'Các nguyên tắc cơ bản về tiền và tài chính',
    'Quan hệ kinh tế quốc tế',
    'Nguyên lý thống kê kinh tế',
    'Giao nhận vận tải',
    'Đầu tư quốc tế',
    'hanh toán quốc tế',
    'Tin học đại cương ',
    'Bảo hiểm trong kinh doanh',
    'Giáo dục thể chất',
    'Giáo dục quốc phòng',
    'Môi trường kinh doanh',
    'Hành vi tổ chức ',
    'Tiếp thị',
    'Kế toán và tài chính',
    'Chiến lược kinh doanh',
    'Nghệ thuật lãnh đạo và quản lý',
    'Quản trị nguồn nhân lực',
    'Quản trị sản phẩm',
    'Nghiên cứu Marketing',
    'Quản trị kênh phân phối',
    'Marketing nền tảng số',
    'Marketing quốc tế',
    'Marketing dịch vụ',
    'Chiến lược Marketing cho thế giới mạng',
    'Quản trị thương hiệu',
    'Nhượng quyền thương hiệu',
    'Quan hệ công chúng',
    'Quảng cáo và khuyến mại',
    'Tổ chức sự kiện',
    'Phát triển sản phẩm mới',
    'Chuyên ngành Công nghệ thông tin (IT)',
    'Nhập môn lập trình',
    'Lập trình hướng đối tượng',
    'Cấu trúc dữ liệu và giải thuật',
    'Cơ sở dữ liệu',
    'Mạng máy tính, kiến trúc máy tính, hệ điều hành',
];
export const listDay = [
    {
        name: 'Thứ 2',
        id: 'Mon',
    },
    {
        name: 'Thứ 3',
        id: 'Tue',
    },
    {
        name: 'Thứ 4',
        id: 'Wed',
    },
    {
        name: 'Thứ 5',
        id: 'Thu',
    },
    {
        name: 'Thứ 6',
        id: 'Fri',
    },
    {
        name: 'Thứ 7',
        id: 'Sat',
    },
    {
        name: 'Chủ nhật',
        id: 'Sun',
    },
];
export const listTeacher = [
    {
        name: 'Phan Trần Minh Khuê',
        gender: 'Nam',
        course: 'Cơ Sở Lập Trình',
        color: '#cccccc',
        lessonRegister: [
            {
                room: '1',
                day: 'Thứ 2',
                lesson: '1',
            },
            {
                room: '1',
                day: 'Thứ 2',
                lesson: '2',
            },
            {
                room: '1',
                day: 'Thứ 2',
                lesson: '3',
            },
            {
                room: '1',
                day: 'Thứ 2',
                lesson: '4',
            },
            {
                room: '1',
                day: 'Thứ 3',
                lesson: '8',
            },
            {
                room: '1',
                day: 'Thứ 3',
                lesson: '9',
            },
        ],
    },
    {
        name: 'Hà Minh Tuấn',
        gender: 'Nam',
        course: 'Đại Số Tuyến Tính',
        color: '#ff6707',
        lessonRegister: [
            {
                room: '3',
                day: 'Thứ 2',
                lesson: '2',
            },
            {
                room: '3',
                day: 'Thứ 2',
                lesson: '3',
            },
            {
                room: '3',
                day: 'Thứ 3',
                lesson: '1',
            },
            {
                room: '3',
                day: 'Thứ 3',
                lesson: '2',
            },
            {
                room: '3',
                day: 'Thứ 3',
                lesson: '3',
            },
            {
                room: '4',
                day: 'Thứ 3',
                lesson: '4',
            },
        ],
    },
    {
        name: 'Hồ Hướng Thiên',
        gender: 'Nam',
        course: 'Nhập Môn Tin Học',
        color: '#333333',
        lessonRegister: [
            {
                room: '1',
                day: 'Thứ 4',
                lesson: '1',
            },
            {
                room: '1',
                day: 'Thứ 4',
                lesson: '2',
            },
            {
                room: '1',
                day: 'Thứ 4',
                lesson: '3',
            },
            {
                room: '1',
                day: 'Thứ 4',
                lesson: '4',
            },
        ],
    },
];

export const rooms = {
    room_1: {
        Mon: {
            lesson_1: { name: 'Phan Trần Minh Khuê', gender: 'Male', course: 'Cơ Sở Lập Trình', color: '#cccccc' },
            lesson_2: { name: 'Phan Trần Minh Khuê', gender: 'Male', course: 'Cơ Sở Lập Trình', color: '#cccccc' },
            lesson_3: { name: 'Phan Trần Minh Khuê', gender: 'Male', course: 'Cơ Sở Lập Trình', color: '#cccccc' },
            lesson_4: { name: 'Phan Trần Minh Khuê', gender: 'Male', course: 'Cơ Sở Lập Trình', color: '#cccccc' },
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Tue: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: { name: 'Phan Trần Minh Khuê', gender: 'Male', course: 'Cơ Sở Lập Trình', color: '#cccccc' },
            lesson_9: { name: 'Phan Trần Minh Khuê', gender: 'Male', course: 'Cơ Sở Lập Trình', color: '#cccccc' },
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Wed: {
            lesson_1: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_2: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_3: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_4: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Thu: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Fri: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sat: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sun: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
    },

    room_2: {
        Mon: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Tue: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Wed: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Thu: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Fri: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sat: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sun: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
    },
    room_3: {
        Mon: {
            lesson_1: {},
            lesson_2: { name: 'Hà Minh Tuấn', gender: 'Male', course: 'Đại Số Tuyến Tính', color: '#ff6707' },
            lesson_3: { name: 'Hà Minh Tuấn', gender: 'Male', course: 'Đại Số Tuyến Tính', color: '#ff6707' },
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Tue: {
            lesson_1: { name: 'Hà Minh Tuấn', gender: 'Male', course: 'Đại Số Tuyến Tính', color: '#ff6707' },
            lesson_2: { name: 'Hà Minh Tuấn', gender: 'Male', course: 'Đại Số Tuyến Tính', color: '#ff6707' },
            lesson_3: { name: 'Hà Minh Tuấn', gender: 'Male', course: 'Đại Số Tuyến Tính', color: '#ff6707' },
            lesson_4: { name: 'Hà Minh Tuấn', gender: 'Male', course: 'Đại Số Tuyến Tính', color: '#ff6707' },
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Wed: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Thu: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Fri: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sat: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sun: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
    },
    room_4: {
        Mon: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_8: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_9: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_10: { name: 'Hồ Hướng Thiên', gender: 'Male', course: 'Nhập Môn Tin Học', color: '#333333' },
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Tue: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Wed: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Thu: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Fri: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sat: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sun: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
    },
    room_5: {
        Mon: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Tue: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Wed: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Thu: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Fri: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sat: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
        Sun: {
            lesson_1: {},
            lesson_2: {},
            lesson_3: {},
            lesson_4: {},
            lesson_5: {},
            lesson_6: {},
            lesson_7: {},
            lesson_8: {},
            lesson_9: {},
            lesson_10: {},
            lesson_11: {},
            lesson_12: {},
            lesson_13: {},
            lesson_14: {},
            lesson_15: {},
            lesson_16: {},
            lesson_17: {},
        },
    },
};

export const listLesson = [
    { name: '', id: 'lesson_0' },
    { name: 'Tiết 1', id: 'lesson_1' },
    { name: 'Tiết 2', id: 'lesson_2' },
    { name: 'Tiết 3', id: 'lesson_3' },
    { name: 'Tiết 4', id: 'lesson_4' },
    { name: 'Tiết 5', id: 'lesson_5' },
    { name: 'Tiết 6', id: 'lesson_6' },
    { name: 'Tiết 7', id: 'lesson_7' },
    { name: 'Tiết 8', id: 'lesson_8' },
    { name: 'Tiết 9', id: 'lesson_9' },
    { name: 'Tiết 10', id: 'lesson_10' },
    { name: 'Tiết 11', id: 'lesson_11' },
    { name: 'Tiết 12', id: 'lesson_12' },
    { name: 'Tiết 13', id: 'lesson_13' },
    { name: 'Tiết 14', id: 'lesson_14' },
    { name: 'Tiết 15', id: 'lesson_15' },
    { name: 'Tiết 16', id: 'lesson_16' },
    { name: '', id: 'lesson_17' },
];
export const listTime = [
    '',
    '07:00',
    '07:50',
    '08:40',
    '09:30',
    '10:20',
    '11:00',
    '13:00',
    '13:50',
    '14:40',
    '15:30',
    '16:20',
    '17:00',
    '18:00',
    '18:50',
    '19:40',
    '20:05',
    '',
];
